{{- if (include "codimd.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "codimd.fullname" . }}
  labels:
    app: {{ template "codimd.name" . }}
    chart: {{ template "codimd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.sessionSecret }}
  sessionSecret: {{ .Values.sessionSecret | b64enc | quote }}
  {{- else }}
  sessionSecret: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.openid.enabled }}
    {{- range $key, $value := .Values.auth.openid }}
      {{- if ne $key "enabled" }}
        {{- range $k, $v := $value }}
          {{- if contains "secret" $k }}
  {{ $key }}Secret: {{ $v | b64enc | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.storage.s3.amazon.enabled }}
  amazonSecret: {{ .Values.storage.s3.amazon.secret_access_key | b64enc | quote }}
  {{- else if .Values.storage.s3.minio.enabled }}
  minioSecret: {{ .Values.storage.s3.minio.secret_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.oauth2.enabled }}
  oauth2Secret: {{ .Values.auth.oauth2.client_secret | b64enc | quote }}
  {{- end }}
{{- end -}}
